image:
- Visual Studio 2017
- Ubuntu1804

stack: python 3

environment:
  PY_DIR: C:\Python37-x64
  MINGW_DIR: C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin

clone_depth: 25

build: off

init:
- cmd: set PATH=%PY_DIR%;%PY_DIR%\Scripts;%MINGW_DIR%;%PATH%

- cmd: cinst -y ninja
- sh: sudo apt-get -yq update > /dev/null
- sh: sudo apt-get install -yq --no-install-suggests --no-install-recommends ninja-build > /dev/null

install:
# had to pip here since stack: python 3 didn't take effect in init:
- pip install meson
- meson setup build
- meson install -C build

test_script: meson test -C build

artifacts:
- path: build/rpncalc.exe
  name: WindowsExecutable

deploy:
  description: 'Executables for Fortran 2018 RPN Calculator'
  draft: true
  provider: GitHub
  artifact: build/rpncalc.exe
  on:
    branch: master
    APPVEYOR_REPO_TAG: true
